#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Mesh IA workflow: volumetric 3D object from an image or a prompt
(TRELLIS.2-4B GGUF via trellis.cpp, Vulkan backend). Validated by the user
on 2026-09-06 on the repo helmet (res 512 = 10 min 44 s, res 1024 = 55 min).

Unlike mesh3d (extruded parametric shapes), this workflow produces a real
AI-inferred closed volume, with PBR textures — helmets, statues, creatures,
complex props. Output: GLB + Blender control renders + recap sheet.
"""

import json
import os
import time
from datetime import datetime
from typing import Any, Dict

from core.config import slugifier_texte
from core.mesh_ia import (
    DUREES_ESTIMEES,
    assembler_planche,
    generer_mesh_trellis,
    reduire_mesh_blender,
    rendre_controle_blender,
    verifier_trellis,
)
from workflows.base import BaseWorkflow, WorkflowRegistry


def _formater_duree(secondes: float) -> str:
    """Formats a duration as "X min YY s" (or "YY s" under a minute)."""
    total = int(round(secondes))
    if total < 60:
        return f"{total} s"
    mm, ss = divmod(total, 60)
    return f"{mm} min {ss:02d} s"


@WorkflowRegistry.register
class MeshIaWorkflow(BaseWorkflow):
    """Image or prompt → AI 3D object (.glb PBR) via TRELLIS.2 GGUF (Vulkan)."""

    name = "mesh_ia"
    description = ("Volumetric AI 3D object from an image or a prompt "
                   "(TRELLIS.2-4B or Pixal3D GGUF, Vulkan): PBR GLB + Blender control renders")

    emoji = "🧊"

    # CLI declarations (audit §2.2, migration from the flat table of cli/parser.py:
    # help/defaults taken as-is, unchanged surface).
    PARAMETRES = [
        dict(flags=("--res",), type=int, choices=[512, 1024, 1536], default=512,
             help="3D generation resolution for mesh_ia (TRELLIS.2): 512 = iteration ~11 min, 1024 = master ~55 min (default: 512)."),
        dict(flags=("--faces-cible",), type=int, default=0,
             help="Face-count target of the \"game\" GLB for mesh_ia: OPTIONAL Blender decimation (master kept; default: 0 = no reduction). Guidelines: 30000 = hero item seen up close • 10000 = scenery prop • 3000 = repeated clutter • >=8000 for very curved silhouettes."),
        dict(flags=("--mesh-moteur",), dest="mesh_moteur", choices=["trellis", "pixal3d"], default="trellis",
             help="mesh_ia engine: trellis = TRELLIS.2 (default, validated 2026-09-06) | pixal3d = TRELLIS.2 fine-tune with pixel-aligned projection (flat colors + crisp lettering in ONE pass, no repaint; VALIDATED 2026-10-02 'super'; 512 ≈ 14 min, +32 % vs trellis; weights vegax87/Pixal3D). (--moteur itself is taken by voix_off.)"),
        dict(flags=("--fov",), type=float, default=None,
             help="Horizontal FOV in degrees — pixal3d only (default: engine 49.13°; a wrong FOV shows as silhouette drift/thickness, not a crash)."),
    ]

    def run(self, params: Dict[str, Any]) -> Dict[str, Any]:
        input_image = params.get("input")
        prompt = params.get("prompt")
        if not input_image and not prompt:
            raise ValueError("Provide -i <image.png> or a prompt (the source image will be generated by Flux then cut out).")

        moteur = params.get("mesh_moteur") or "trellis"
        fov = params.get("fov")
        fov = float(fov) if fov is not None else None

        ok, manquants = verifier_trellis(moteur=moteur)
        if not ok:
            raise EnvironmentError("Missing TRELLIS.2 components: " + " ; ".join(manquants))

        res = int(params.get("res") or 512)
        if res not in (512, 1024, 1536):
            raise ValueError(f"Invalid resolution {res} (512, 1024 or 1536).")
        seed = params.get("seed")
        if seed is not None:
            seed = int(seed)

        nom_base = slugifier_texte(
            params.get("output") or (prompt if prompt else os.path.splitext(os.path.basename(input_image))[0])
        )[:60]
        dossier = os.path.join("output", "mesh_ia", nom_base)
        os.makedirs(dossier, exist_ok=True)

        # 1. Source image: provided, or generated + cut out by the generate workflow
        #    (a pre-matted image keeps its alpha → no BiRefNet cutout on the trellis side).
        t_debut = time.time()
        duree_image = 0.0
        if not input_image:
            self.log("Generating the source image (Flux Vulkan) + cutout…", "🖼️")
            t_img = time.time()
            wf_gen = WorkflowRegistry.get("generate")(self.config)
            params_gen = dict(params)
            params_gen["output"] = nom_base
            params_gen["output_dir"] = dossier
            res_gen = wf_gen.run(params_gen)
            input_image = res_gen["output_path"]
            duree_image = time.time() - t_img
        elif not os.path.exists(input_image):
            raise FileNotFoundError(f"Source image not found: {input_image}")

        # 2. TRELLIS.2 / Pixal3D : image → GLB PBR
        estime = DUREES_ESTIMEES.get(res, "?")
        if moteur == "pixal3d":
            self.log(f"Pixal3D image → 3D (res {res}, one-pass flat colors; 512 ≈ 14 min on RX 6950 XT) — output: {dossier}", "🧊")
        else:
            self.log(f"TRELLIS.2 image → 3D (res {res}, {estime} on RX 6950 XT) — output: {dossier}", "🧊")
        resultat = generer_mesh_trellis(
            image_path=input_image,
            output_dir=dossier,
            nom_base=nom_base,
            res=res,
            seed=seed,
            moteur=moteur,
            fov=fov,
        )
        self.log(f"PBR GLB generated in {_formater_duree(resultat['duree_s'])}: {resultat['glb']}", "✅")

        # 3. OPTIONAL mesh reduction for the runtime (master kept)
        #    trellis outputs 150-300 k faces: pass --faces-cible N (e.g.: 30000)
        #    for a decimated "game" GLB; default = no reduction.
        faces_cible = params.get("faces_cible")
        faces_cible = 0 if faces_cible is None else int(faces_cible)
        glb_controle = resultat["glb"]
        duree_reduction = 0.0
        if faces_cible > 0:
            glb_jeu = os.path.join(dossier, f"{nom_base}_{res}_jeu.glb")
            t_red = time.time()
            red = reduire_mesh_blender(resultat["glb"], glb_jeu, faces_cible)
            duree_reduction = time.time() - t_red
            if red:
                resultat["glb_jeu"] = red["glb"]
                resultat["faces_avant"] = red["faces_avant"]
                resultat["faces_apres"] = red["faces_apres"]
                self.log(f"Reduction: {red['faces_avant']} → {red['faces_apres']} faces "
                         f"(target {faces_cible}): {red['glb']}", "📉")
                glb_controle = red["glb"]

        # 4. Blender control renders + recap sheet
        t_rendus = time.time()
        vues = rendre_controle_blender(glb_controle, dossier, f"{nom_base}_{res}")
        duree_rendus = time.time() - t_rendus
        planche = None
        if len(vues) == 4:
            planche = assembler_planche(
                source_png=input_image,
                vues=vues,
                base_png=resultat.get("base_png"),
                sortie=os.path.join(dossier, f"{nom_base}_{res}_planche.png"),
            )
            self.log(f"Control sheet: {planche}", "📷")

        taille_mo = os.path.getsize(resultat["glb"]) / (1024 * 1024)
        self.log(f"Object ready for Godot: {resultat['glb']} ({taille_mo:.1f} MB, res {res})", "🎮")

        # 5. Duration recap + information sheet written next to the outputs
        durees = {
            "image_source_s": round(duree_image, 1),
            "trellis_s": round(resultat["duree_s"], 1),
            "reduction_s": round(duree_reduction, 1),
            "rendus_s": round(duree_rendus, 1),
            "totale_s": round(time.time() - t_debut, 1),
        }
        etapes = [f"image {_formater_duree(durees['image_source_s'])}" if duree_image > 0 else None,
                  f"TRELLIS {_formater_duree(durees['trellis_s'])}",
                  f"reduction {_formater_duree(durees['reduction_s'])}" if faces_cible > 0 else None,
                  f"renders {_formater_duree(durees['rendus_s'])}"]
        self.log("⏱️ Durations: " + " • ".join(e for e in etapes if e)
                 + f" • TOTAL {_formater_duree(durees['totale_s'])} (res {res})", "⏱️")

        infos = {
            "workflow": "mesh_ia",
            "date": datetime.now().isoformat(timespec="seconds"),
            "res": res,
            "moteur": moteur,
            "fov": fov,
            "seed": resultat.get("seed"),
            "faces_cible": faces_cible or None,
            "faces_avant": resultat.get("faces_avant"),
            "faces_apres": resultat.get("faces_apres"),
            "durees_s": durees,
            "image_source": input_image,
            "glb": resultat["glb"],
            "glb_jeu": resultat.get("glb_jeu"),
            "base_png": resultat.get("base_png"),
            "planche": planche,
            "vues": vues,
        }
        chemin_infos = os.path.join(dossier, f"{nom_base}_{res}_infos.json")
        with open(chemin_infos, "w", encoding="utf-8") as f:
            json.dump(infos, f, indent=2, ensure_ascii=False)

        resultat.update({
            "vues": vues,
            "planche": planche,
            "image_source": input_image,
            "dossier": dossier,
            "durees": durees,
            "infos_json": chemin_infos,
        })
        return resultat
